channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=25.0
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - numpy==1.26.2
  - pandas==2.2.3
  - psutil==5.9.6
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
